descriptor-schema-version: "2.2"

info:
  name: PythonCapp
  description: "Python application with platform dependent python module"
  version: "1.0"
  author-link: "http://www.cisco.com"
  author-name: "Cisco Systems"

app:
  # Indicate app type (vm, paas, lxc etc.,)
  cpuarch: "x86_64"
  type: docker
  resources:
    profile: c1.small

    network:
      -
        interface-name: eth0
        ports:
            tcp: [8000]
            udp: [10000]

# Specify runtime and startup
  startup:
    rootfs: rootfs.tar
    target: ["/opt/app/loop.sh"]
